pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"

# LF2 Online engine — lives under app/javascript/engine/.
pin "engine/asset-registry", to: "engine/asset-registry.js"
pin "engine/network", to: "engine/network.js"
pin "engine/network-digest", to: "engine/network-digest.js"
pin "engine/network-timing", to: "engine/network-timing.js"
pin_all_from "app/javascript/engine/core",        under: "engine/core"
pin_all_from "app/javascript/engine/third_party", under: "engine/third_party"
pin_all_from "app/javascript/engine/pack",        under: "engine/pack"

# engine/Game/* — explicit pins (pin_all_from doesn't pick up directory renames)
pin "engine/Game/AI",                  to: "engine/Game/AI.js"
pin "engine/Game/background",          to: "engine/Game/background.js"
pin "engine/Game/character-behaviors",  to: "engine/Game/character-behaviors.js"
pin "engine/Game/character-states",    to: "engine/Game/character-states.js"
pin "engine/Game/character",           to: "engine/Game/character.js"
pin "engine/Game/dom-query",           to: "engine/Game/dom-query.js"
pin "engine/Game/effect-set",          to: "engine/Game/effect-set.js"
pin "engine/Game/factories",           to: "engine/Game/factories.js"
pin "engine/Game/global",              to: "engine/Game/global.js"
pin "engine/Game/living-object",       to: "engine/Game/living-object.js"
pin "engine/Game/loader-config",       to: "engine/Game/loader-config.js"
pin "engine/Game/loader",              to: "engine/Game/loader.js"
pin "engine/Game/manager",             to: "engine/Game/manager.js"
pin "engine/Game/manager-dialogs",     to: "engine/Game/manager-dialogs.js"
pin "engine/Game/match",               to: "engine/Game/match.js"
pin "engine/Game/match/battle-mode",  to: "engine/Game/match/battle-mode.js"
pin "engine/Game/match/hud",          to: "engine/Game/match/hud.js"
pin "engine/Game/match/objects",       to: "engine/Game/match/objects.js"
pin "engine/Game/match/stage-mode",   to: "engine/Game/match/stage-mode.js"
pin "engine/Game/mechanics",           to: "engine/Game/mechanics.js"
pin "engine/Game/music",               to: "engine/Game/music.js"
pin "engine/Game/projectile",          to: "engine/Game/projectile.js"
pin "engine/Game/recorder",            to: "engine/Game/recorder.js"
pin "engine/Game/resource-path",       to: "engine/Game/resource-path.js"
pin "engine/Game/scene",               to: "engine/Game/scene.js"
pin "engine/Game/select",              to: "engine/Game/select.js"
pin "engine/Game/soundpack",           to: "engine/Game/soundpack.js"
pin "engine/Game/entity-sprite",       to: "engine/Game/entity-sprite.js"
pin "engine/Game/touchcontroller",     to: "engine/Game/touchcontroller.js"
pin "engine/Game/ui/battle_setup",         to: "engine/Game/ui/battle_setup.js"
pin "engine/Game/ui/championship",         to: "engine/Game/ui/championship.js"
pin "engine/Game/ui/character_selection",  to: "engine/Game/ui/character_selection.js"
pin "engine/Game/ui/demo_setup",           to: "engine/Game/ui/demo_setup.js"
pin "engine/Game/ui/frontpage",            to: "engine/Game/ui/frontpage.js"
pin "engine/Game/ui/gameplay",             to: "engine/Game/ui/gameplay.js"
pin "engine/Game/ui/lobby",                to: "engine/Game/ui/lobby.js"
pin "engine/Game/ui/network_game",         to: "engine/Game/ui/network_game.js"
pin "engine/Game/ui/recording",            to: "engine/Game/ui/recording.js"
pin "engine/Game/ui/settings",             to: "engine/Game/ui/settings.js"
pin "engine/Game/ui/stage_select",         to: "engine/Game/ui/stage_select.js"
pin "engine/Game/weapon",              to: "engine/Game/weapon.js"
pin "engine/Game/weapon-drink",        to: "engine/Game/weapon-drink.js"
