pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"

# LF2 Online engine — lives under app/javascript/engine/.
pin "engine/asset-registry", to: "engine/asset-registry.js"
pin "engine/network", to: "engine/network.js"
pin_all_from "app/javascript/engine/core",        under: "engine/core"
pin_all_from "app/javascript/engine/third_party", under: "engine/third_party"
pin_all_from "app/javascript/engine/pack",        under: "engine/pack"

# engine/Game/* — explicit pins (pin_all_from doesn't pick up directory renames)
pin "engine/Game/AI",                  to: "engine/Game/AI.js"
pin "engine/Game/background",          to: "engine/Game/background.js"
pin "engine/Game/character-behaviors",  to: "engine/Game/character-behaviors.js"
pin "engine/Game/character-states",    to: "engine/Game/character-states.js"
pin "engine/Game/character",           to: "engine/Game/character.js"
pin "engine/Game/effect",              to: "engine/Game/effect.js"
pin "engine/Game/factories",           to: "engine/Game/factories.js"
pin "engine/Game/global",              to: "engine/Game/global.js"
pin "engine/Game/entity",              to: "engine/Game/entity.js"
pin "engine/Game/loader-config",       to: "engine/Game/loader-config.js"
pin "engine/Game/loader",              to: "engine/Game/loader.js"
pin "engine/Game/manager",             to: "engine/Game/manager.js"
pin "engine/Game/manager-dialogs",     to: "engine/Game/manager-dialogs.js"
pin "engine/Game/match",               to: "engine/Game/match.js"
pin "engine/Game/mechanics",           to: "engine/Game/mechanics.js"
pin "engine/Game/projectile",          to: "engine/Game/projectile.js"
pin "engine/Game/recorder",            to: "engine/Game/recorder.js"
pin "engine/Game/scene",               to: "engine/Game/scene.js"
pin "engine/Game/soundpack",           to: "engine/Game/soundpack.js"
pin "engine/Game/sprite",              to: "engine/Game/sprite.js"
pin "engine/Game/touchcontroller",     to: "engine/Game/touchcontroller.js"
pin "engine/Game/util",                to: "engine/Game/util.js"
pin "engine/Game/weapon",              to: "engine/Game/weapon.js"
pin "engine/Game/weapon-drink",        to: "engine/Game/weapon-drink.js"
